version: '3.8'
services:
  assistant:
    build: .
    container_name: assistant
    ports:
      - "8000:8000"
    environment:
      - METRICS_DEV_LOG=/app/metrics_dev.jsonl
    volumes:
      - ./:/app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/grafana-dashboard.json:ro
