global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'assistant'
    static_configs:
      - targets: ['assistant:8000']

rule_files:
  - /etc/prometheus/alert_rules.yml
