# GPU Dockerfile template for v003
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3-pip
COPY . /app
WORKDIR /app
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu121
RUN pip install --no-cache-dir bitsandbytes transformers sentencepiece soundfile torchaudio timm fastapi uvicorn[standard]
EXPOSE 8000
CMD ["python3","server.py"]